# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'

services:
  production:
    hostname: app-production
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      PORT: "8081"
    volumes:
      - type: bind
        source: .
        target: /api
    working_dir: /api
    ports:
      - "8081:8081"
    command: bash -c "./scripts/production.sh"

  development:
    hostname: app-development
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - type: bind
        source: .
        target: /api
    working_dir: /api
    ports:
      - "8080:8080"
    command: bash -c "go mod download && make serve"
